image: "archlinux:latest"

before_script:
    - >
      pacman -Syu --needed --noconfirm
      make base-devel python
      python-pytest python-pytest-cov python-pytest-pacman
      python-sphinx python-pylint


stages:
  - lint
  - test
  - doc


lint:
  script:
    - make lint


test:
  script:
    - make build
    - PYTEST_OPTIONS=--junitxml=report.xml make test
  artifacts:
    when: always
    reports:
      junit: report.xml
